# cmd: docker compose up -d
version: '3'

services:
  sefora-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "sefora_psw"
    ports:
      - "5432:5432"
    restart: unless-stopped

  ############################################
  #keycloak:
  #  image: quay.io/keycloak/keycloak:latest
  #  ports:
  #    - "9090:8080"
  #  environment:
  #    KEYCLOAK_ADMIN: admin
  #    KEYCLOAK_ADMIN_PASSWORD: admin
  #  command: start-dev
  #  restart: unless-stopped
  ############################################